- name: Install ACL package
  apt:
    name: acl
    state: present

- name: Install application.
  apt: 
    deb: "{{ app_deb_package }}"

- name: Create app user.
  user:
    name: "{{ app_user }}"
    comment: App user
    system: yes

- name: Chown Apps directory
  file:
    dest: "{{ app_directory }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: yes

- name: Chown npm cache directory
  file:
    path: /var/www/
    state: directory
    recurse: yes
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Check if composer.json exists
  stat:
    path: "{{ app_directory }}/composer.json"
  register: run_composer

- name: Validate PHP framework
  include_tasks: validation.yml

- become: true
  become_user: "{{ app_user }}"
  block:
    - name: Set bitbucket auth for private composer packages.
      shell: "composer config --global --auth bitbucket-oauth.bitbucket.org {{ bitbucket_consumer_key }} {{ bitbucket_consumer_secret }}"
      when:
        - bitbucket_consumer_key != ""
        - bitbucket_consumer_secret != ""
        - run_composer.stat.exists

    - name: Composer Install.
      composer:
        command: install
        no_dev: no
        working_dir: "{{ app_directory }}"
      when: run_composer.stat.exists

    - include: testing.yml

    - name: Check if npm package.json exists
      stat:
        path: "{{ app_directory }}/package.json"
      register: run_npm

    - name: npm install
      command: "npm install"
      args:
        chdir: "{{ app_directory }}"
      when: npm_install and run_npm.stat.exists

    - name: npm run prod
      command: "npm run prod"
      args:
        chdir: "{{ app_directory }}"
      when: npm_install and run_npm.stat.exists

    - include: behat.yml

    - name: Composer install to remove dev dependecies.
      composer:
        command: install
        working_dir: "{{ app_directory }}"
      when: run_composer.stat.exists

    - include: env.yml

    - name: Craft Security Key Generate.
      shell: 'php craft setup/security-key'
      args:
        chdir: "{{ app_directory }}"
      when: fact_craftcms_version | length > 0 and app_env.APP_KEY is not defined

    - name: Artisan Key Generate.
      shell: 'php artisan key:generate'
      args:
        chdir: "{{ app_directory }}"
      when: fact_laravel_version | length > 0 and app_env.APP_KEY is not defined

    - name: Configure laravel cronjob
      cron:
        name: Laravel Cron
        user: "{{ app_user }}"
        job: "cd {{ app_directory }} && php artisan schedule:run >> /dev/null 2>&1"
      when: fact_laravel_version | length > 0
